### ISSUE TITLE
Make modifier key configurable

### ISSUE THREAD

**Issue by jhartz** [joeltg/visual_history#2]
I am used to using the Ctrl key for moving the cursor in text boxes (ctrl + left/right to jump back/forward one word), but this conflicts with that. It would be handy to have a preference to select a different key, such as Alt or Ctrl+Alt, etc.

**Comment by joeltg** [comment]
So far as I know, chrome extensions can't programmatically change their own hotkey bindings, they can only declare defaults in their manifest. 
But the user can remap or disable keyboard shortcuts in chrome://extensions, I believe! (you might have to enable developer mode first)
