### ISSUE TITLE
History is incorrect

### ISSUE THREAD

**Issue by willlma** [joeltg/visual_history#3]
I really like this concept and extension. Sometimes the history tree is wrong. I started in Google Maps, then did a Google search, as seen by the back button's dropdown. Extension shows it backward ![screenshot 2015-12-21 10 15 27](https://cloud.githubusercontent.com/assets/4404401/11927296/d7866334-a7cb-11e5-8809-937d062bfec1.JPG)

**Comment by joeltg** [comment]
This will be fixed in V2.0, coming to the Web Store soon!
